language = {
    description = "Description",
    adddesc = "Add a Description To The Item",
    removefavo = "Remove From Favourite",
    removefavo2 = "Remove Recipie From favourite list",
    addfavo = "Add To Favourite",
    addfavo2 = "Add Recipie to favourite list",
    craft = "Craft",
    craftitem = "Craft Item",
    craftingmenu = "Crafting Menu",
    alreadyadded = "Already added",
    confirm = "Confirm",
    amount = "Amount",
    invalidamount = "Invalid Amount",
    youdesc = "Your Description",
    cantusewords = "Cant use these words...",
    favo = "Favourites",
    favo2 = "Your Favourite Recipes",
    craftingexp = "Crafting Experince: ",
    crafting = "Crafting",
    youfailed = "You Failed To Craft And Lost The Items",
    placing = "Placing...",
    alreadyplaced = "You Already have something placed, remove it first",
    cantuseintown = "Cant Use in Towns",
    successful = "Crafting Successful",
    notenoughmats = "Not enough material for this recipe",
    cantcarry = "Cant carry more items",
    
    -- Discord webhook messages
    charactername = "Character Name",
    itemcrafting = "item player is crafting",
    steamid = "Steam ID", 
    steamname = "Steam name",
    itemsused = "items used to craft",

}