Config = {}
Config.keys = {
    ["G"] = 0x760A9C6F,
    ["4"] = 0x8F9F9E58,
    ["DOWN"] = 0x05CA7C52,
    ["UP"] = 0x6319DB71,
    ["LEFT"] = 0xA65EBAB4,
    ["RIGHT"] = 0xDEB34313,
    ["1"] = 0xE6F612E4,
    ["2"] = 0x1CE6D9EB,
    ["B"] = 0x4CC0E2FE,

}
Config.denysceneinhideout = true 
Config.scenecommand = "scene" -- /scene
Config.mecommand = "me" -- /me
Config.ooccommand = "ooc" -- /ooc
Config.statuscommand = "status" -- /status
Config.stopdisplay = "cstatus" -- /cstatus stop displaying status.
Config.id = "id" -- /id
Config.cash = "cash" -- /cash
Config.scenevisabilitydistance = 5
Config.removejobs = {"marshal","police","newspaper"}
Config.webhook = ""
Config.joblock = false
Config.allowjobs = {"newspaper"}
Config.Language = {
    helloworld = "Aim And Press G To Register Scene",
    confirm = "Confirm",
    displaytext = "Display Text",
    pressup = "Press Up To Move Text",
    pressleft = "Press Left To Move Text",
    pressright = "Press Right To Move Text",
    pressdown = "Press Down To Move Text",
    press1 = "Press 1 To Move Text",
    press2 = "Press 2 To Move Text",
    pressg = "Press G To Confirm",
    pressg2 = "Press 4 To Remove",
    pressb = "Press B To Cancel",
    scenereg = "Scene Registered",
    sceneremoved = "Scene Removed",
    ooc = "OOC: ",
    stat = "Status: ",
    cash = "Cash: $ ",
    id = "ID: ",
    notinhideout = "Cant place scene in hideout",
    notjob = "You Dont Have The Right Job",
}