---@type NssPedMenuPedsConfig
PedsConfig = {}

-- add or remove whatever you want
-- List of human male NPC models available for selection

PedsConfig.HumanMale = {
    "cs_oddfellowspinhead",
    "mp_u_m_m_outlaw_mpvictim_01",
    "A_M_M_SkpPrisoner_01",
    "cs_mp_teddybrown",
    "mp_u_m_m_saloonbrawler_13",
    "cs_welshfighter",
    "cs_aberdeenpigfarmer",
    "u_m_o_oldcajun_01",
    "A_M_M_ARMTOWNFOLK_01",
    "A_M_M_ASBMINER_04",
    "A_M_M_MIDDLESDTOWNFOLK_02",
    "A_M_M_SDCHINATOWN_01",
    "CS_CORNWALLTRAINCONDUCTOR",
    "CS_MP_BOUNTYHUNTER",
    "S_M_M_BWMWORKER_01",
    "U_M_M_CHELONIANJUMPER_01",
    "U_M_M_CZPHOMESTEADFATHER_01",
    "U_M_M_LNSWORKER_01",
    "U_M_M_RHDBARTENDER_01",
    "U_M_M_TUMBUTCHER_01",
    "U_M_M_VALDOCTOR_01",
    "U_M_O_VHTEXOTICSHOPKEEPER_01",
    "U_M_Y_CZPHOMESTEADSON_03",
    "U_M_M_WTCCOWBOY_04",
    "U_M_M_VALBARBER_01",
    "U_M_M_TUMTRAINSTATIONWORKER_01",
    "U_M_M_RHDSHERIFF_01",
    "U_M_M_RHDBACKUPDEPUTY_01",
    "U_M_M_LNSWORKER_02",
    "U_M_M_EMRFARMHAND_03",
    "S_M_M_DISPATCHPOLICE_01",
    "MSP_TRAINROBBERY2_MALES_01",
    "MSP_GANG3_MALES_01",
}

-- List of human female NPC models available for selection
PedsConfig.HumanFemale = {
    "a_f_m_btcobesewomen_01",
    "a_f_m_sdobesewomen_01",
    "cs_abigailroberts",
    "cs_fire_breather",
    "cs_marylinton",
    "cs_mp_bountyhunter",
    "cs_penelopebraithwaite",
    "cs_sistercalderon",
    "mp_campdef_hennigans_females_01",
    "mp_de_u_f_m_doverhill_01",
    "mp_g_f_m_laperlegang_01",
    "mp_intro_females_01",
    "mp_u_f_m_bountytarget_003",
    "mp_u_f_m_laperlevipunmasked_02",
    "mp_u_f_m_legendarybounty_03",
    "u_f_m_valtownfolk_02",
    "cs_brendacrawley",
    "cs_cancan_04",
    "cs_creepyoldlady",
}

-- List of event NPC models available for selection
PedsConfig.EventPeds = {
    "a_f_m_armcholeracorpse_01",
    "a_f_m_unicorpse_01",
    "a_m_m_armcholeracorpse_01",
    "a_m_m_unicorpse_01",
    "cs_charlessmith",
    "cs_chelonianmaster",
    "cs_crackpotrobot",
    "cs_genstoryfemale",
    "cs_genstorymale",
    "cs_joebutler",
    "cs_magnifico",
    "cs_odprostitute",
    "cs_swampfreak",
    "cs_vampire",
    "loansharking_undertaker_females_01",
    "mes_sadie4_males_01",
    "mp_g_f_m_armyoffear_01",
    "mp_g_m_m_armyoffear_01",
    "mp_g_m_m_uniswamp_01",
    "mp_predator",
    "msp_saloon1_females_01",
    "re_injuredrider_males_01",
    "re_savageaftermath_females_01",
    "re_savageaftermath_males_01",
    "re_savagewagon_males_01",
    "re_townburial_males_01",
    "re_voice_females_01",
}

-- List of wild animal models available for selection
-- please do not add birds, this does not work well and usually not at all.
PedsConfig.WildAnimals = {
    "a_c_alligator_01",
    "a_c_alligator_02",
    "a_c_alligator_03",
    "a_c_armadillo_01",
    "a_c_badger_01",
    "a_c_bearblack_01",
    "a_c_bear_01",
    "a_c_beaver_01",
    "a_c_bighornram_01",
    "a_c_boarlegendary_01",
    "a_c_boar_01",
    "a_c_buck_01",
    "a_c_buffalo_01",
    "a_c_buffalo_tatanka_01",
    "a_c_bull_01",
    "a_c_cougar_01",
    "a_c_deer_01",
    "a_c_elk_01",
    "a_c_fox_01",
    "a_c_frogbull_01",
    "a_c_gilamonster_01",
    "a_c_goat_01",
    "a_c_iguanadesert_01",
    "a_c_iguana_01",
    "a_c_lionmangy_01",
    "a_c_moose_01",
    "a_c_panther_01",
    "a_c_pig_01",
    "a_c_possum_01",
    "a_c_pronghorn_01",
    "a_c_rabbit_01",
    "a_c_raccoon_01",
    "a_c_sheep_01"
}

PedsConfig.Birds = {
    "a_c_eagle_01",
    "A_C_CaliforniaCondor_01",
    "A_C_Cormorant_01",
    "A_C_Egret_01",
    "A_C_Hawk_01",
    "A_C_Heron_01",
    "A_C_Owl_01",
    "A_C_Parrot_01",
    "A_C_Pelican_01",
    "A_C_Seagull_01",
    "A_C_Raven_01"
}

-- List of dog and cat models available for selection
PedsConfig.DogCat = {
    "a_c_dogamericanfoxhound_01",
    "a_c_dogaustraliansheperd_01",
    "a_c_dogbluetickcoonhound_01",
    "a_c_dogcatahoulacur_01",
    "a_c_dogchesbayretriever_01",
    "a_c_dogcollie_01",
    "a_c_doghobo_01",
    "a_c_doghound_01",
    "mp_a_c_dogamericanfoxhound_01",
    "a_c_doghusky_01",
    "a_c_doglab_01",
    "a_c_doglion_01",
    "a_c_dogpoodle_01",
    "a_c_dogrufus_01",
    "a_c_dogstreet_01",
    "re_lostdog_dogs_01",
    "a_c_cat_01",
}

-- List of horse models available for selection
PedsConfig.Horses = {
    "a_c_horsemulepainted_01",
    "a_c_horsemule_01",
    "p_c_horse_01",
    "a_c_horse_americanpaint_greyovero",
    "a_c_horse_americanpaint_overo",
    "a_c_horse_americanpaint_splashedwhite",
    "a_c_horse_americanpaint_tobiano",
    "a_c_horse_americanstandardbred_black",
    "a_c_horse_americanstandardbred_buckskin",
    "a_c_horse_americanstandardbred_lightbuckskin",
    "a_c_horse_americanstandardbred_palominodapple",
    "a_c_horse_americanstandardbred_silvertailbuckskin",
    "a_c_horse_andalusian_darkbay",
    "a_c_horse_andalusian_perlino",
    "a_c_horse_andalusian_rosegray",
    "a_c_horse_appaloosa_blacksnowflake",
    "a_c_horse_appaloosa_blanket",
    "a_c_horse_appaloosa_brownleopard",
    "a_c_horse_appaloosa_fewspotted_pc",
    "a_c_horse_appaloosa_leopard",
    "a_c_horse_appaloosa_leopardblanket",
    "a_c_horse_arabian_black",
    "a_c_horse_arabian_grey",
    "a_c_horse_arabian_redchestnut",
    "a_c_horse_arabian_redchestnut_pc",
    "a_c_horse_arabian_rosegreybay",
    "a_c_horse_arabian_warpedbrindle_pc",
    "a_c_horse_arabian_white",
    "a_c_horse_ardennes_bayroan",
    "a_c_horse_ardennes_irongreyroan",
    "a_c_horse_ardennes_strawberryroan",
    "a_c_horse_belgian_blondchestnut",
}