INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('goldnugget', 'Gold Nugget', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('sap', 'Sap', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('emerald', 'Emerald', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('diamond', 'Diamond', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('coal', 'Coal', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('copper', 'Copper', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('syn', 'Syn', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('clay', 'Clay', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('wool', 'Wool', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('potato', 'Potato', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('Wild_Carrot', 'Wild Carrot', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('hwood', 'Hard Wood', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('burialoil', 'Burial Perfume Oil', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('burialwraps', 'Burial Wraps', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('goodbyliquor', 'Good-bye Liquor', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('flowerarrangement', 'Flower Arrangement', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('honey', 'Honey', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('acid', 'Acid', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('joint', 'Joint', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('wine', 'Wine', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('syn', 'Syn', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('goldbar', 'GoldBar', 20, 1, 'item_standard', 1);
INSERT IGNORE INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('shovel', 'Shovel', 20, 1, 'item_standard', 1);