Config = {}
Config.framework = "vorp"--"redemrp" or "vorp" or "qbr" or "qbr2" or "redemrp-reboot" or "rsg"
Config.MenuAlign = "top-right"
Config.Prompts = {
    Prompt1 = 0x05CA7C52,
    PromptSell = 0x6319DB71,
    PromptReset = 0x3F4DC0EF,
}

Config.ResetMissions = {
    enable = true,
    price = 250,
}

Config.DefaultItemEngineTexture = {"menu_textures", "log_gang_bag", "COLOR_GOLD"}
Config.ItemEngineTextures = {
    bread = {"menu_textures", "log_gang_bag", "COLOR_GOLD"},
    water = {"menu_textures", "log_gang_bag", "COLOR_GOLD"},
}

Config.ViewDistancePed = 100.0 
Config.CooldownBetweenMissions = 5
Config.Marker = {
    rgba = {126, 0, 0, 0},
    size = {2.0, 2.0, 0.3},
}

Config.Texts = {
    Prompt1 = "Missions",
    PromptSell = "Sell Horse",
    PromptReset = "Reset Mission",
    --TEXTS
    WildHorse = "Wild Horse",
    HorseThief = "Horse Thief",
    CantSellThis = "Cant sell this type of horse!",
    IgnoredBySeller = "Buyer ignored the horse!",
    NotLookingFor = "Buyer is not willing to buy this horse!",
    NoAnimal = "You must sit on a horse!",
    LeavingSoon = "Buyer is leaving soon, try later!",
    SoldHorse = "Horse sold to the Thief!",
    NoJob = "You dont have the required job!",
    Type = "Mission Type",
    ThiefMissions = "Thief Missions",
    Details = "Details",
    Mission = "Mission",
    SitOnHorse = "Find the Horse and Tame it!",
    DeliverHorse = "Deliver the Horse!",
    FailedMission = "Mission failed!",
    StealHorse = "Find and Steal the horse!",
    AllFinished = "All mission finished!",
    InMission = "You are in a mission!",
    Finished = "Mission finished!",
    CantStartNow = "Cant start now, wait until cooldown expires! (%s)",
    FinishAllFirst = "Finish all missions first!",
    MissionsReseted = "Missions reseted!",
    NoXP = "You dont have enough XP! %s/%s",
    --mission type
    steal = "Horse Stealing",
    collect = "Wild Horse Collect",
    unk = "Unknown",
}

Config.Textures = {
    cross = {"scoretimer_textures", "scoretimer_generic_cross"},
    locked = {"menu_textures","stamp_locked_rank"},
    tick = {"scoretimer_textures","scoretimer_generic_tick"},
    money = {"inventory_items", "money_moneystack"},
    alert = {"menu_textures", "menu_icon_alert"},
}

Config.GPS_Color = `COLOR_GREEN`
Config.MissionAreaBlip = `BLIP_STYLE_FM_EVENT_RADIUS`

Config.NPCClay = {
    coords = {
        {pos = vector4(732.632, 777.465, 128.308, 192.097), blip_enable = true,}, 
        {pos = vector4(87.964, 1225.148, 186.981, 4.450), blip_enable = true, },
        {pos = vector4(733.683, -854.382, 49.070, 289.660), blip_enable = true,}, 
        {pos = vector4(1540.553, -1794.726, 52.104, 346.554), blip_enable = true,}, 
        {pos = vector4(-1505.315, -1636.425, 80.412, 121.727), blip_enable = true,},        
    },
    name = "Clay",
    blip = {sprite = `blip_mp_mission_area_clay`},
    model = `cs_clay`,  
    model_clive = `cs_clive`,
    pos_change_timer = 15, --minutes
    missions = {
        [1] = {
            type = "collect",
            reward = 10, --$
            item_reward = {
                {id = "bread", label = "Bread", amount = 2},
                {id = "water", label = "Water", amount = 1},
            },
            name = "Wild Mustangs",
            desc = "Tame a wild horse for buyer",
            finish_pos = vector3(1431.795, 288.723, 88.397),
            horse = {model = `a_c_horse_mustang_goldendun`, pos = vector3(653.576, 484.340, 119.615)},
            xp = {required = 0, earn = 10},
        },
        [2] = {
            type = "steal",
            reward = 50, --$
            item_reward = {
                {id = "bread", label = "Bread", amount = 2},
                {id = "water", label = "Water", amount = 1},
            },
            name = "Weird Situation",
            desc = "Steal a horse",
            finish_pos = vector3(-344.794, -136.179, 47.454),
            horse = {model = `a_c_horse_gang_sean`, pos = vector(250.569, 318.048, 117.622)},
            guards = { 
                {model = `cs_mp_alfredo_montez`, preset = 1, weapon = `WEAPON_SHOTGUN_REPEATING`, pos = vector4(246.096, 330.821, 119.043, 32.479), name = "Guard"},
                {model = `mp_u_m_m_buyer_regular_06`, preset = 1, weapon = `WEAPON_SHOTGUN_REPEATING`, pos = vector4(257.012, 337.571, 119.530, 44.061), name = "Guard"},
            },
            xp = {required = 10, earn = 20},
        },
        [3] = {
            type = "collect",
            reward = 10, --$
            item_reward = {
                {id = "bread", label = "Bread", amount = 2},
                {id = "water", label = "Water", amount = 1},
            },
            name = "Wild Mustangs #2",
            desc = "Tame a wild horse for buyer",
            finish_pos = vector3(1431.795, 288.723, 88.397),
            horse = {model = `a_c_horse_mustang_tigerstripedbay`, pos = vector3(653.576, 484.340, 119.615)},
            xp = {required = 30, earn = 5},
        },
    },
}

Config.RandomHorseSpawn_Change = 15 --minutes 
Config.RandomHorseSpawn_Blip = `BLIP_STYLE_PROC_MISSION_RADIUS`
Config.RandomHorseSpawns = {
    {pos = vector4(986.184, 519.311, 98.222, 205.5472), model = `a_c_horse_gang_sean`, blip_enable = true},
    {pos = vector4(986.462, 176.111, 108.456, 184.551), model = "random", blip_enable = true},
}

Config.DonkeyEasterEggComment = {chances = 10000, min = 500, max = 600} -- from 1 to chances a random number will be selected, and if the number is between min and max then Easter Egg talk will be triggered by Clay

Config.Horses = {
   [`a_c_donkey_01`] = { name = "Donkey", price = 20, earn_xp = 10},
   [`a_c_horsemulepainted_01`] = { name = "Painted Mule", price = 20},
   [`a_c_horsemule_01`] = { name = "Mule", price = 20},
   [`p_c_horse_01`] = { name = "Horse", price = 20},
   [`a_c_horse_americanpaint_greyovero`] = { name = "American Paint - Grey Overo", price = 100},
   [`a_c_horse_americanpaint_overo`] = { name = "American Paint - Overo", price = 100},
   [`a_c_horse_americanpaint_splashedwhite`] = { name = "American Paint - White", price = 100},
   [`a_c_horse_americanpaint_tobiano`] = { name = "American Paint - Tobian", price = 100},
   [`a_c_horse_americanstandardbred_black`] = { name = "American Standardbred - Black", price = 100},
   [`a_c_horse_americanstandardbred_buckskin`] = { name = "American Standardbred - Buck", price = 100},
   [`a_c_horse_americanstandardbred_lightbuckskin`] = { name = "American Standardbred - Light Buck", price = 100},
   [`a_c_horse_americanstandardbred_palominodapple`] = { name = "American Standardbred - Palomino", price = 100},
   [`a_c_horse_americanstandardbred_silvertailbuckskin`] = { name = "American Standardbred - Silvertail", price = 100},
   [`a_c_horse_andalusian_darkbay`] = { name = "Andalusian - darkbay", price = 50},
   [`a_c_horse_andalusian_perlino`] = { name = "Andalusian - perlino", price = 50},
   [`a_c_horse_andalusian_rosegray`] = { name = "Andalusian - rosegray", price = 50},
   [`a_c_horse_appaloosa_blacksnowflake`] = { name = "Appaloosa - blacksnowflake", price = 75},
   [`a_c_horse_appaloosa_blanket`] = { name = "Appaloosa - blanket", price = 75},
   [`a_c_horse_appaloosa_brownleopard`] = { name = "Appaloosa - brownleopard", price = 75},
   [`a_c_horse_appaloosa_fewspotted_pc`] = { name = "Appaloosa - fewspotted_pc", price = 75},
   [`a_c_horse_appaloosa_leopard`] = { name = "Appaloosa - leopard", price = 75},
   [`a_c_horse_appaloosa_leopardblanket`] = { name = "Appaloosa - leopardblanket", price = 75},
   [`a_c_horse_arabian_black`] = { name = "Arabian - black", price = 120},
   [`a_c_horse_arabian_grey`] = { name = "Arabian - grey", price = 120},
   [`a_c_horse_arabian_redchestnut`] = { name = "Arabian - redchestnut", price = 120},
   [`a_c_horse_arabian_redchestnut_pc`] = { name = "Arabian - redchestnut_pc", price = 120},
   [`a_c_horse_arabian_rosegreybay`] = { name = "Arabian - rosegreybay", price = 120},
   [`a_c_horse_arabian_warpedbrindle_pc`] = { name = "Arabian - warpedbrindle_pc", price = 120},
   [`a_c_horse_arabian_white`] = { name = "Arabian - white", price = 120},
   [`a_c_horse_ardennes_bayroan`] = { name = "Ardennes - bayroan", price = 65},
   [`a_c_horse_ardennes_irongreyroan`] = { name = "Ardennes - irongreyroan", price = 65},
   [`a_c_horse_ardennes_strawberryroan`] = { name = "Ardennes - strawberryroan", price = 65},
   [`a_c_horse_belgian_blondchestnut`] = { name = "Belgian - blondchestnut", price = 60},
   [`a_c_horse_belgian_mealychestnut`] = { name = "Belgian - mealychestnut", price = 60},
   [`a_c_horse_breton_grullodun`] = { name = "Breton - grullodun", price = 60},
   [`a_c_horse_breton_mealydapplebay`] = { name = "Breton - mealydapplebay", price = 60},
   [`a_c_horse_breton_redroan`] = { name = "Breton - redroan", price = 60},
   [`a_c_horse_breton_sealbrown`] = { name = "Breton - sealbrown", price = 60},
   [`a_c_horse_breton_sorrel`] = { name = "Breton - sorrel", price = 60},
   [`a_c_horse_breton_steelgrey`] = { name = "Breton - steelgrey", price = 60},
   [`a_c_horse_buell_warvets`] = { name = "a_c_horse_buell_warvets", price = 60},
   [`a_c_horse_criollo_baybrindle`] = { name = "Criollo - baybrindle", price = 50},
   [`a_c_horse_criollo_bayframeovero`] = { name = "Criollo - bayframeovero", price = 50},
   [`a_c_horse_criollo_blueroanovero`] = { name = "Criollo - blueroanovero", price = 50},
   [`a_c_horse_criollo_dun`] = { name = "Criollo - dun", price = 50},
   [`a_c_horse_criollo_marblesabino`] = { name = "Criollo - marblesabino", price = 50},
   [`a_c_horse_criollo_sorrelovero`] = { name = "Criollo - sorrelovero", price = 50},
   [`a_c_horse_dutchwarmblood_chocolateroan`] = { name = "Dutch Warmblood - chocolateroan", price = 40},
   [`a_c_horse_dutchwarmblood_sealbrown`] = { name = "Dutch Warmblood - sealbrown", price = 40},
   [`a_c_horse_dutchwarmblood_sootybuckskin`] = { name = "Dutch Warmblood - sootybuckskin", price = 40},
   [`a_c_horse_eagleflies`] = { name = "Gang Horse - eagle flies", price = 40},
   [`a_c_horse_gang_bill`] = { name = "Gang Horse - bill", price = 40},
   [`a_c_horse_gang_charles`] = { name = "Gang Horse - charles", price = 40},
   [`a_c_horse_gang_charles_endlesssummer`] = { name = "Gang Horse - charles_endlesssummer", price = 40},
   [`a_c_horse_gang_dutch`] = { name = "Gang Horse - dutch", price = 40},
   [`a_c_horse_gang_hosea`] = { name = "Gang Horse - hosea", price = 40},
   [`a_c_horse_gang_javier`] = { name = "Gang Horse - javier", price = 40},
   [`a_c_horse_gang_john`] = { name = "Gang Horse - john", price = 40},
   [`a_c_horse_gang_karen`] = { name = "Gang Horse - karen", price = 40},
   [`a_c_horse_gang_kieran`] = { name = "Gang Horse - kieran", price = 40},
   [`a_c_horse_gang_lenny`] = { name = "Gang Horse - lenny", price = 40},
   [`a_c_horse_gang_micah`] = { name = "Gang Horse - micah", price = 40},
   [`a_c_horse_gang_sadie`] = { name = "Gang Horse - sadie", price = 40},
   [`a_c_horse_gang_sadie_endlesssummer`] = { name = "Gang Horse - sadie_endlesssummer", price = 40},
   [`a_c_horse_gang_sean`] = { name = "Gang Horse - sean", price = 40},
   [`a_c_horse_gang_trelawney`] = { name = "Gang Horse - trelawney", price = 40},
   [`a_c_horse_gang_uncle`] = { name = "Gang Horse - uncle", price = 40},
   [`a_c_horse_gang_uncle_endlesssummer`] = { name = "Gang Horse - uncle_endlesssummer", price = 40},
   [`a_c_horse_hungarianhalfbred_darkdapplegrey`] = { name = "Hungarian Halfbreed - darkdapplegrey", price = 55},
   [`a_c_horse_hungarianhalfbred_flaxenchestnut`] = { name = "Hungarian Halfbreed - flaxenchestnut", price = 55},
   [`a_c_horse_hungarianhalfbred_liverchestnut`] = { name = "Hungarian Halfbreed - liverchestnut", price = 55},
   [`a_c_horse_hungarianhalfbred_piebaldtobiano`] = { name = "Hungarian Halfbreed - piebaldtobiano", price = 55},
   [`a_c_horse_john_endlesssummer`] = { name = "Gang Horse - John 2", price = 30},
   [`a_c_horse_kentuckysaddle_black`] = { name = "Kentucky Saddler - black", price = 30},
   [`a_c_horse_kentuckysaddle_buttermilkbuckskin_pc`] = { name = "Kentucky Saddler - buttermilkbuckskin_pc", price = 30},
   [`a_c_horse_kentuckysaddle_chestnutpinto`] = { name = "Kentucky Saddler - chestnutpinto", price = 30},
   [`a_c_horse_kentuckysaddle_grey`] = { name = "Kentucky Saddler - grey", price = 30},
   [`a_c_horse_kentuckysaddle_silverbay`] = { name = "Kentucky Saddler - silverbay", price = 30},
   [`a_c_horse_kladruber_black`] = { name = "Kladruber - black", price = 30},
   [`a_c_horse_kladruber_cremello`] = { name = "Kladruber - cremello", price = 30},
   [`a_c_horse_kladruber_dapplerosegrey`] = { name = "Kladruber - dapplerosegrey", price = 30},
   [`a_c_horse_kladruber_grey`] = { name = "Kladruber - grey", price = 30},
   [`a_c_horse_kladruber_silver`] = { name = "Kladruber - silver", price = 30},
   [`a_c_horse_kladruber_white`] = { name = "Kladruber - white", price = 30},
   [`a_c_horse_missourifoxtrotter_amberchampagne`] = { name = "Missouri Foxtrotter - amberchampagne", price = 65},
   [`a_c_horse_missourifoxtrotter_sablechampagne`] = { name = "Missouri Foxtrotter - sablechampagne", price = 65},
   [`a_c_horse_missourifoxtrotter_silverdapplepinto`] = { name = "Missouri Foxtrotter - silverdapplepinto", price = 65},
   [`a_c_horse_morgan_bay`] = { name = "Morgan - bay", price = 20},
   [`a_c_horse_morgan_bayroan`] = { name = "Morgan - bayroan", price = 20},
   [`a_c_horse_morgan_flaxenchestnut`] = { name = "Morgan - flaxenchestnut", price = 20},
   [`a_c_horse_morgan_liverchestnut_pc`] = { name = "Morgan - liverchestnut_pc", price = 20},
   [`a_c_horse_morgan_palomino`] = { name = "Morgan - palomino", price = 20},
   [`a_c_horse_mp_mangy_backup`] = { name = "Mangy Horse", price = 20},
   [`a_c_horse_murfreebrood_mange_01`] = { name = "Murfree Horse - 01", price = 20},
   [`a_c_horse_murfreebrood_mange_02`] = { name = "Murfree Horse - 02", price = 20},
   [`a_c_horse_murfreebrood_mange_03`] = { name = "Murfree Horse - 03", price = 20},
   [`a_c_horse_mustang_goldendun`] = { name = "Mustang - goldendun", price = 45},
   [`a_c_horse_mustang_grullodun`] = { name = "Mustang - grullodun", price = 45},
   [`a_c_horse_mustang_tigerstripedbay`] = { name = "Mustang - tigerstripedbay", price = 45},
   [`a_c_horse_mustang_wildbay`] = { name = "Mustang - wildbay", price = 45},
   [`a_c_horse_nokota_blueroan`] = { name = "Nokota - blueroan", price = 55},
   [`a_c_horse_nokota_reversedappleroan`] = { name = "Nokota - reversedappleroan", price = 55},
   [`a_c_horse_nokota_whiteroan`] = { name = "Nokota - whiteroan", price = 55},
   [`a_c_horse_shire_darkbay`] = { name = "Shire - darkbay", price = 90},
   [`a_c_horse_shire_lightgrey`] = { name = "Shire - lightgrey", price = 90},
   [`a_c_horse_shire_ravenblack`] = { name = "Shire - ravenblack", price = 90},
   [`a_c_horse_suffolkpunch_redchestnut`] = { name = "Suffolk Punch - redchestnut", price = 85},
   [`a_c_horse_suffolkpunch_sorrel`] = { name = "Suffolk Punch - sorrel", price = 85},
   [`a_c_horse_tennesseewalker_blackrabicano`] = { name = "Tennessee Walker - blackrabicano", price = 25},
   [`a_c_horse_tennesseewalker_chestnut`] = { name = "Tennessee Walker - chestnut", price = 25},
   [`a_c_horse_tennesseewalker_dapplebay`] = { name = "Tennessee Walker - dapplebay", price = 25},
   [`a_c_horse_tennesseewalker_flaxenroan`] = { name = "Tennessee Walker - flaxenroan", price = 25},
   [`a_c_horse_tennesseewalker_goldpalomino_pc`] = { name = "Tennessee Walker - goldpalomino_pc", price = 25},
   [`a_c_horse_tennesseewalker_mahoganybay`] = { name = "Tennessee Walker - mahoganybay", price = 25},
   [`a_c_horse_tennesseewalker_redroan`] = { name = "Tennessee Walker - redroan", price = 25},
   [`a_c_horse_thoroughbred_blackchestnut`] = { name = "Thoroughbred - blackchestnut", price = 35},
   [`a_c_horse_thoroughbred_bloodbay`] = { name = "Thoroughbred - bloodbay", price = 35},
   [`a_c_horse_thoroughbred_brindle`] = { name = "Thoroughbred - brindle", price = 35},
   [`a_c_horse_thoroughbred_dapplegrey`] = { name = "Thoroughbred - dapplegrey", price = 35},
   [`a_c_horse_thoroughbred_reversedappleblack`] = { name = "Thoroughbred - reversedappleblack", price = 35},
   [`a_c_horse_turkoman_darkbay`] = { name = "Turkoman - darkbay", price = 40},
   [`a_c_horse_turkoman_gold`] = { name = "Turkoman - gold", price = 40},
   [`a_c_horse_turkoman_silver`] = { name = "Turkoman - silver", price = 40},
   [`a_c_horse_winter02_01`] = { name = "a_c_horse_winter02_01", price = 40},
   [`MP_A_C_HORSECORPSE_01`] = { name = "MP_A_C_HORSECORPSE_01", price = 40},
   [`mp_horse_owlhootvictim_01`] = { name = "Owlhool Horse", price = 75},
   [`a_c_horse_norfolkroadster_black`] = { name = "Norfolk Roadster - black", price = 75},
   [`a_c_horse_norfolkroadster_dappledbuckskin`] = { name = "Norfolk Roadster - dappledbuckskin", price = 75},
   [`a_c_horse_norfolkroadster_piebaldroan`] = { name = "Norfolk Roadster - piebaldroan", price = 75},
   [`a_c_horse_norfolkroadster_rosegrey`] = { name = "Norfolk Roadster - rosegrey", price = 75},
   [`a_c_horse_norfolkroadster_speckledgrey`] = { name = "Norfolk Roadster - speckledgrey", price = 75},
   [`a_c_horse_norfolkroadster_spottedtricolor`] = { name = "Norfolk Roadster - spottedtricolor", price = 75},
   [`a_c_horse_gypsycob_palominoblagdon`] = { name = "Gypsycob - palominoblagdon", price = 110},
   [`a_c_horse_gypsycob_piebald`] = { name = "Gypsycob - piebald", price = 110},
   [`a_c_horse_gypsycob_skewbald`] = { name = "Gypsycob - skewbald", price = 110},
   [`a_c_horse_gypsycob_splashedbay`] = { name = "Gypsycob - splashedbay", price = 110},
   [`a_c_horse_gypsycob_splashedpiebald`] = { name = "Gypsycob - splashedpiebald", price = 110},
   [`a_c_horse_gypsycob_whiteblagdon`] = { name = "Gypsycob - whiteblagdon", price = 110},
   [`a_c_horse_missourifoxtrotter_blacktovero`] = { name = "Missouri Foxtrotter - blacktovero", price = 55},
   [`a_c_horse_missourifoxtrotter_blueroan`] = { name = "Missouri Foxtrotter - blueroan", price = 55},
   [`a_c_horse_missourifoxtrotter_buckskinbrindle`] = { name = "Missouri Foxtrotter - buckskinbrindle", price = 55},
   [`a_c_horse_missourifoxtrotter_dapplegrey`] = { name = "Missouri Foxtrotter - dapplegrey", price = 55},
   [`a_c_horse_mustang_blackovero`] = { name = "Mustang - blackovero", price = 60},
   [`a_c_horse_mustang_buckskin`] = { name = "Mustang - buckskin", price = 60},
   [`a_c_horse_mustang_chestnuttovero`] = { name = "Mustang - chestnuttovero", price = 60},
   [`a_c_horse_mustang_reddunovero`] = { name = "Mustang - reddunovero", price = 60},
   [`a_c_horse_turkoman_black`] = { name = "Turkoman - black", price = 45},
   [`a_c_horse_turkoman_chestnut`] = { name = "Turkoman - chestnut", price = 45},
   [`a_c_horse_turkoman_grey`] = { name = "Turkoman - grey", price = 45},
   [`a_c_horse_turkoman_perlino`] = { name = "Turkoman - perlino", price = 45},
}

--for talking ped comment, for other horse models, it has built in custom comment depending on the breed 
Config.AverageHorseModels = {
    [`a_c_horse_tennesseewalker_blackrabicano`] = {},
    [`a_c_horse_tennesseewalker_dapplebay`] = {},
    [`a_c_horse_tennesseewalker_chestnut`] = {},
    [`a_c_horse_tennesseewalker_flaxenroan`] = {},
    [`a_c_horse_tennesseewalker_mahoganybay`] = {},
    [`a_c_horse_tennesseewalker_goldpalomino_pc`] = {},
    [`a_c_horse_tennesseewalker_redroan`] = {},
    [`a_c_horse_winter02_01`] = {},
}
Config.PoorHorseModels = {
    [`a_c_horsemulepainted_01`] = {},
    [`a_c_horsemule_01`] = {},
    [`p_c_horse_01`] = {},
    [`a_c_horse_mp_mangy_backup`] = {},
    [`a_c_horse_murfreebrood_mange_01`] = {},
    [`a_c_horse_murfreebrood_mange_02`] = {},
    [`a_c_horse_murfreebrood_mange_03`] = {},
    [`mp_horse_owlhootvictim_01`] = {},
}
Config.QualityHorseModels = {
    [`a_c_horse_breton_redroan`] = {},
    [`a_c_horse_breton_sealbrown`] = {},
    [`a_c_horse_breton_sorrel`] = {},
    [`a_c_horse_breton_steelgrey`] = {},
    [`a_c_horse_buell_warvets`] = {},
    [`a_c_horse_criollo_baybrindle`] = {},
    [`a_c_horse_criollo_bayframeovero`] = {},
    [`a_c_horse_criollo_blueroanovero`] = {},
    [`a_c_horse_criollo_dun`] = {},
    [`a_c_horse_criollo_marblesabino`] = {},
    [`a_c_horse_criollo_sorrelovero`] = {},
    [`a_c_horse_kladruber_black`] = {},
    [`a_c_horse_kladruber_cremello`] = {},
    [`a_c_horse_kladruber_dapplerosegrey`] = {},
    [`a_c_horse_kladruber_silver`] = {},
    [`a_c_horse_kladruber_grey`] = {},
    [`a_c_horse_kladruber_white`] = {},
    [`a_c_horse_norfolkroadster_black`] = {},
    [`a_c_horse_norfolkroadster_dappledbuckskin`] = {},
    [`a_c_horse_norfolkroadster_piebaldroan`] = {},
    [`a_c_horse_norfolkroadster_rosegrey`] = {},
    [`a_c_horse_norfolkroadster_speckledgrey`] = {},
    [`a_c_horse_norfolkroadster_spottedtricolor`] = {},
    [`a_c_horse_gypsycob_palominoblagdon`] = {},
    [`a_c_horse_gypsycob_piebald`] = {},
    [`a_c_horse_gypsycob_skewbald`] = {},
    [`a_c_horse_gypsycob_splashedbay`] = {},
    [`a_c_horse_gypsycob_splashedpiebald`] = {},
    [`a_c_horse_gypsycob_whiteblagdon`] = {},
    [`a_c_horse_breton_grullodun`] = {},
    [`a_c_horse_breton_mealydapplebay`] = {},
}
Config.UniqueHorseModels = {
    [`a_c_horse_eagleflies`] = {},
    [`a_c_horse_gang_bill`] = {},
    [`a_c_horse_gang_charles`] = {},
    [`a_c_horse_gang_charles_endlesssummer`] = {},
    [`a_c_horse_gang_dutch`] = {},
    [`a_c_horse_gang_hosea`] = {},
    [`a_c_horse_gang_javier`] = {},
    [`a_c_horse_gang_john`] = {},
    [`a_c_horse_gang_karen`] = {},
    [`a_c_horse_gang_kieran`] = {},
    [`a_c_horse_gang_lenny`] = {},
    [`a_c_horse_gang_micah`] = {},
    [`a_c_horse_gang_sadie`] = {},
    [`a_c_horse_gang_sadie_endlesssummer`] = {},
    [`a_c_horse_gang_sean`] = {},
    [`a_c_horse_gang_trelawney`] = {},
    [`a_c_horse_gang_uncle`] = {},
    [`a_c_horse_gang_uncle_endlesssummer`] = {},
    [`a_c_horse_john_endlesssummer`] = {},
}
